[package]
name = "aws-toolkit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.24.1", features = ["full"] }
rusoto_core = "0.48.0"
rusoto_sqs = "0.48.0"